Repository triton-inference-server/vllm_backend, pull requests merged in 2024-08, with the labels that each got.

#55 refactor: Remove explicit callings to garbage collect
  src/model.py
Labels: PR: refactor

#54 perf: Check for cancellation on response thread
  src/model.py
Labels: PR: perf

#53 feat: Add vLLM counter metrics access through Triton
  README.md
  ci/L0_backend_vllm/metrics_test/test.sh
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  ci/L0_backend_vllm/test.sh
  ci/L0_backend_vllm/vllm_backend/test.sh
  samples/model_repository/vllm_model/1/model.json
  src/model.py
  src/utils/metrics.py
Labels: enhancement

#56 feat: Report histogram metrics to Triton metrics server
  README.md
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  src/utils/metrics.py
Labels: enhancement

#60 feat: Add vLLM counter metrics access through Triton (#53)
  README.md
  ci/L0_backend_vllm/metrics_test/test.sh
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  ci/L0_backend_vllm/test.sh
  ci/L0_backend_vllm/vllm_backend/test.sh
  samples/model_repository/vllm_model/1/model.json
  src/model.py
  src/utils/metrics.py
Labels: cherry-pick

#59 feat: Report histogram metrics to Triton metrics server (#58)
  README.md
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  src/utils/metrics.py
Labels: cherry-pick

#61 feat: Report more histogram metrics
  README.md
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  src/model.py
  src/utils/metrics.py
Labels: enhancement
