Repository triton-inference-server/vllm_backend, pull requests merged in 2024-12, with the labels that each got.

#73 feat: Auto unload model if vLLM health check failed
  README.md
  ci/L0_backend_vllm/metrics_test/test.sh
  ci/L0_check_health_vllm/check_health_test.py
  ci/L0_check_health_vllm/mock_async_llm_engine.py
  ci/L0_check_health_vllm/test.sh
  docs/health_check.md
  src/model.py
Labels: PR: feat

#76 perf: Upgrade vLLM version to 0.6.3.post1
  ci/L0_backend_vllm/metrics_test/test.sh
  ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
  ci/L0_check_health_vllm/mock_async_llm_engine.py
  ci/L0_check_health_vllm/test.sh
  src/model.py
  src/utils/metrics.py
Labels: PR: perf

#79 ci: Fix L0_model_control_stress_vllm
  samples/client.py
Labels: bug
